### ISSUE TITLE
throwing error not defined 

### ISSUE THREAD

**Issue by drnareshchauhan** [jaspreet145/QuizApp#1]
Hi it is throwing error when I try to register using front end 
can you pls guide me
![image](https://user-images.githubusercontent.com/71005257/139111468-4820bc71-b259-4a70-8248-f89bfb9dd343.png)
thank you !

**Comment by ajay856** [comment]
i to face this problem please help to solve this

**Comment by jaspreet145** [comment]
please change API port and change API path to `http://localhost:4000/user/add`
make Corresponding DB changes as well for the call.
The app requires two env variables:
ACCESS_TOKEN_SECRET: for JWT
ATLAS_URI: for DB connection string.
Hope this helps!
